export const MATCH_COUNTRY_ISO: Record<string, string> = {
  'Algeria':          'DZ',
  'Alemania':         'DE',
  'Arabia Saudita':   'SA',
  'Argelia':          'DZ',
  'Argentina':        'AR',
  'Australia':        'AU',
  'Austria':          'AT',
  'Bélgica':          'BE',
  'Brasil':           'BR',
  'Cabo Verde':       'CV',
  'Canadá':           'CA',
  'Catar':            'QA',
  'Colombia':         'CO',
  'Corea del Sur':    'KR',
  'Costa de Marfil':  'CI',
  'Croacia':          'HR',
  'Curazao':          'CW',
  'Ecuador':          'EC',
  'Egipto':           'EG',
  'Escocia':          'GB-SCT',
  'España':           'ES',
  'Estados Unidos':   'US',
  'Francia':          'FR',
  'Ghana':            'GH',
  'Haití':            'HT',
  'Inglaterra':       'GB-ENG',
  'Irán':             'IR',
  'Japón':            'JP',
  'Jordania':         'JO',
  'Marruecos':        'MA',
  'México':           'MX',
  'Noruega':          'NO',
  'Nueva Zelanda':    'NZ',
  'países Bajos':     'NL',
  'Países Bajos':     'NL',
  'Panamá':           'PA',
  'Paraguay':         'PY',
  'Portugal':         'PT',
  'Senegal':          'SN',
  'Sudáfrica':        'ZA',
  'Suiza':            'CH',
  'Túnez':            'TN',
  'Uruguay':          'UY',
  'Uzbekistán':       'UZ',
}
